# Nombre interno del proyecto Flutter
name: swipe_gallery

# Descripción corta del propósito de la app
description: "A gallery cleaner using Swipe like Tinder"

# Evita que se publique por accidente en pub.dev
publish_to: 'none'

# Versión de la app (mayor.menor.parche+número_de_compilación)
version: 1.0.0+1

# Define la versión mínima del SDK de Dart necesario
environment:
  sdk: ^3.7.2

# Paquetes que la app necesita para funcionar
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8         # Iconos estilo iOS (opcional)
  photo_manager: ^3.0.0           # Acceso a la galería y permisos
  flutter_card_swiper: ^7.0.2     # Swipe estilo Tinder

# Dependencias usadas solo durante desarrollo o pruebas
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0           # Reglas recomendadas para buen estilo de código

# Configuración específica para Flutter
flutter:
  uses-material-design: true      # Permite usar Material Icons
